"""empty message

Revision ID: c393f60bedb8
Revises: eaa4d8164cf6
Create Date: 2023-01-09 20:00:20.931465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c393f60bedb8'
down_revision = 'eaa4d8164cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('sumclose', sa.Integer(), nullable=False),
    sa.Column('nasclose', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
